In [1]:
# PyPi Repository

import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
student_marks = [42, 49, 12, 20, 30]

In [5]:
type(student_marks)

list

In [6]:
student_marks_np = np.array([42, 49, 12, 20, 30])

In [7]:
type(student_marks_np)

numpy.ndarray

nd --> n-dimensional

In [8]:
print(student_marks)

[42, 49, 12, 20, 30]


In [9]:
print(student_marks_np)

[42 49 12 20 30]


In [10]:
student_marks_np

array([42, 49, 12, 20, 30])

In [11]:
student_marks

[42, 49, 12, 20, 30]

## Indexing in Numpy

In [12]:
student_marks_np[0]

42

In [13]:
student_marks_np[:3]

array([42, 49, 12])

In [14]:
student_marks_np[2:4]

array([12, 20])

In [15]:
student_marks_np[::2]

array([42, 12, 30])

In [16]:
student_marks_np[::-1]

array([30, 20, 12, 49, 42])

## Numpy Operations

In [17]:
length = len(student_marks)
sum_student_marks = sum(student_marks)

average = sum_student_marks / length

print(average)

30.6


In [18]:
np.mean(student_marks_np)

30.6

In [19]:
sum(student_marks_np)

153

In [20]:
np.sum(student_marks_np)

153

In [22]:
# Cumulative Summation

print(student_marks_np)

np.cumsum(student_marks_np)

[42 49 12 20 30]


array([ 42,  91, 103, 123, 153])

In [23]:
# Exponents and Logs

np.exp([1,2,3,4])

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [25]:
np.log([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

array([1., 2., 3., 4.])

## Multi Dimensional Array

In [27]:
# Unicode String in Bytes
np.array(["Sachin", "Rahul"])

array(['Sachin', 'Rahul'], dtype='<U6')

In [28]:
student_marks = np.array([[20,30,40], [10,20,30], [40,50,45]])

In [29]:
student_marks

array([[20, 30, 40],
       [10, 20, 30],
       [40, 50, 45]])

In [35]:
student_marks[student_marks>40]

array([50, 45])

In [31]:
student_marks>40

array([[False, False, False],
       [False, False, False],
       [False,  True,  True]])

In [36]:
student_marks[student_marks > np.mean(student_marks)]

array([40, 40, 50, 45])

In [39]:
student_marks[(student_marks > 20) & (student_marks < 40)]

array([30, 30])

In [41]:
student_marks[(student_marks < 10) | (student_marks > 40)]

array([50, 45])

## Advanced Indexing

In [42]:
student_data = np.array([
    [18, 85, 88, 92],  # Student 1
    [20, 75, 85, 80],  # Student 2
    [19, 95, 90, 94],  # Student 3
    [21, 78, 85, 88],  # Student 4
    [22, 82, 88, 87]   # Student 5
])

In [43]:
# Give me all rows of 1st Column
student_data[:, 0]

array([18, 20, 19, 21, 22])

In [45]:
# Give me all rows of 4th Column 
student_data[:, 3]

array([92, 80, 94, 88, 87])

In [47]:
# Give me first row of all the columns
student_data[0, :]

array([18, 85, 88, 92])

In [50]:
student_data

array([[18, 85, 88, 92],
       [20, 75, 85, 80],
       [19, 95, 90, 94],
       [21, 78, 85, 88],
       [22, 82, 88, 87]])

In [52]:
# Give me all rows of 1st to 3rd column
student_data[:, 0:3]

array([[18, 85, 88],
       [20, 75, 85],
       [19, 95, 90],
       [21, 78, 85],
       [22, 82, 88]])

In [54]:
# Give me first row of all the columns
student_data[:2, :]

array([[18, 85, 88, 92],
       [20, 75, 85, 80]])

In [56]:
# Getting first row and last column
student_data[0, 3]

92

In [62]:
a = student_marks[:,:1]

In [66]:
a

array([[20],
       [10],
       [40]])

In [63]:
b = student_marks[:,0]

In [67]:
b

array([20, 10, 40])

In [64]:
a.shape

(3, 1)

In [65]:
b.shape

(3,)

In [69]:
student_data = np.array([
    [18, 85, 88, 92],  # Student 1
    [20, 75, 85, 80],  # Student 2
    [19, 95, 90, 94],  # Student 3
    [21, 78, 85, 88],  # Student 4
    [22, 82, 88, 87]   # Student 5
])

In [70]:
np.where(student_data < 70, "Grade C", "Grade A")

array([['Grade C', 'Grade A', 'Grade A', 'Grade A'],
       ['Grade C', 'Grade A', 'Grade A', 'Grade A'],
       ['Grade C', 'Grade A', 'Grade A', 'Grade A'],
       ['Grade C', 'Grade A', 'Grade A', 'Grade A'],
       ['Grade C', 'Grade A', 'Grade A', 'Grade A']], dtype='<U7')

In [71]:
np.where(student_data < 90, np.where(student_data>70, "Grade B", "Grade C"), "Grade A")

array([['Grade C', 'Grade B', 'Grade B', 'Grade A'],
       ['Grade C', 'Grade B', 'Grade B', 'Grade B'],
       ['Grade C', 'Grade A', 'Grade A', 'Grade A'],
       ['Grade C', 'Grade B', 'Grade B', 'Grade B'],
       ['Grade C', 'Grade B', 'Grade B', 'Grade B']], dtype='<U7')

In [72]:
student_data = np.array([
    [18, 85, 88, 92],  # Student 1
    [20, 75, 85, 80],  # Student 2
    [19, 95, 90, 94],  # Student 3
    [21, 78, 85, 88],  # Student 4
    [22, 82, 88, 87]   # Student 5
])

In [74]:
conditions = [
    (student_data >= 90),
    (student_data >=70) & (student_data <90),
    (student_data >=50) & (student_data <70),
    (student_data <50)
]

output = [
    "Grade A",
    "Grade B",
    "Grade C",
    "Grade D"
]

In [75]:
np.select(conditions, output)

array([['Grade D', 'Grade B', 'Grade B', 'Grade A'],
       ['Grade D', 'Grade B', 'Grade B', 'Grade B'],
       ['Grade D', 'Grade A', 'Grade A', 'Grade A'],
       ['Grade D', 'Grade B', 'Grade B', 'Grade B'],
       ['Grade D', 'Grade B', 'Grade B', 'Grade B']], dtype='<U7')

# Reshaping Numpy Arrays

In [79]:
list(range(1,13))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [81]:
array1d = np.arange(1,13)

In [89]:
array1d.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [90]:
array1d.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [91]:
array1d.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [100]:
array_2d = array1d.reshape(6,2)

In [99]:
np.reshape([10,20,30,40], (2,2))

array([[10, 20],
       [30, 40]])

In [101]:
array_2d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

### Flattening of array

In [102]:
array_2d.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [104]:
array_2d.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
# Xray images - person1.dcm (Dicom), raw, tiff

In [116]:
array_2d.reshape(3,2,2) #First Dimension, Second Dimension, Third Dimension

# First Dimension = Batch, Depth
# Second Dimension = Rows
# Third Dimension = Columns

array([[[ 5,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 20],
        [11, 12]]])

In [107]:
array_2d.reshape(5,3)

ValueError: cannot reshape array of size 12 into shape (5,3)

In [112]:
array_2d

array([[ 5,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [114]:
array_2d[4,1] = 20

In [115]:
array_2d

array([[ 5,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 20],
       [11, 12]])

In [117]:
array_3d = array_2d.reshape(3,2,2)

In [118]:
array_3d

array([[[ 5,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 20],
        [11, 12]]])

In [124]:
#Multi index concept
array_3d[2][0][1]=30

In [125]:
array_3d

array([[[ 5,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 30],
        [11, 12]]])

In [126]:
#Single index(Slicing)
array_3d[2,0,1]

30

In [127]:
# Range of 0-1
np.random.random((2,2))

array([[0.60776448, 0.3541954 ],
       [0.91706075, 0.62746055]])

In [151]:
# Range of 10,100
np.random.randint(10,100, (4,3))

array([[26, 64, 28],
       [99, 35, 76],
       [76, 92, 63],
       [22, 50, 42]])

In [152]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [153]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [161]:
np.full((4,3), 5.)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [156]:
array_3 = np.full((4,3), 3)
array_4 = np.full((4,3), 4)

In [159]:
array_3

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [160]:
array_4

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [158]:
np.add(array_3, array_4)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [162]:
np.subtract(array_3, array_4)

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [164]:
np.multiply(array_3, array_4)

array([[12, 12, 12],
       [12, 12, 12],
       [12, 12, 12],
       [12, 12, 12]])

In [166]:
np.dot(array_3, array_4.reshape(3,4))

array([[36, 36, 36, 36],
       [36, 36, 36, 36],
       [36, 36, 36, 36],
       [36, 36, 36, 36]])

In [168]:
a = [1,2,3,4,5]
b = [1,4,5,4,7]

np.equal(a,b)

array([ True, False, False,  True, False])

In [171]:
a = [1,2,3,4,5]
b = [1,2,3,4,5]
np.array_equal(a,b)

True