# Numpy Handson

Numpy means Numerical Python

Numpy was created by Travis Oliphant in the year 2005

# 1. Create a numpy array with numpy.array module and with a data type integer and float.

In [1]:
import numpy as np

a=np.array([1,2,3,4,500,600,700,800] ,dtype="int" )
print(a)

[  1   2   3   4 500 600 700 800]


In [5]:
a=np.array([1,2,3,4,500,600,700,800] ,dtype="float" )
print(a)

[  1.   2.   3.   4. 500. 600. 700. 800.]


In [3]:
print(1.0)

1.0


In [10]:
# if our array contains decimals and dtype is given as int, will rounding takes place?

arr1=np.array([12.5 , 45.55 , 999.999 , 120 , 5,6,7 ] ,dtype="int")
print(arr1)

# Without Rounding

print(arr1.ndim)

[ 12  45 999 120   5   6   7]
1


# 2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively. Also, print the shape and dimensions of the numpy arrays created above.


In [ ]:
'''
The dimensionality of array depends on Number of square bracket your are using.
'''

In [13]:
# 0d array
arr=np.array(120)
print(arr)

print(arr.shape)  # to check the shape
print(arr.ndim)  # to check the dimensionality of the array

120
()
0


In [12]:
# Empty 2d array
arr2=np.array([[  ]])
print(arr2.ndim)

# Empty 3d array
arr3=np.array([[[  ]]])
print(arr3.ndim)

2
3


In [14]:
# 1d array
arr1=np.array([1,2,3,4.4 , 5.5 , 6.6])
print(arr1.shape)
print(arr1.ndim)

(6,)
1


In [15]:
# 2d array
arr2d = np.array([ [1,2,3],[4,5,6]])
print(arr2d)

print(arr2d.shape)  # ( no of rows , no of columns)
print(arr2d.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [18]:
#3d array  ( Combine more than 1 2d array to create a 3d array)

arr3=np.array([  [[1,2,3],[4,5,6]]  , [[11,22,33],[44,55,66]] ])
print(arr3)
print(arr3.ndim)

print(arr3.shape)   #( no of 2d array used , no of rows , no of columns)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]
3
(2, 2, 3)


In [ ]:
# 4d array  ( combine more than 1 3d array)

# Homework

# arr4.shape     #( no of 3d arrays used (layers),  no of 2d array inside 3d array , no of rows , no of columns)

# 3. Create a 2x3, 3x3, and 4x4 identity matrix using numpy.


In [22]:
# 2x2 meand 2 rows 2 columns
# 3x3 means 3 rows 3 columns

# Identity matrix means all diagonal elements will be 1 and all Non-diagonal elemets will be 0

arr2=np.identity(2)  # 2x2
print(arr2)

arr3=np.identity(3)  # 3x3
print(arr3)

arr4=np.identity(4,dtype="int")  #4x4
print(arr4)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


# 4. Create a numpy array with shape 2x5 that has all the elements as zero.

In [24]:
k=np.zeros( (2,5),dtype="int")
print(k)

[[0 0 0 0 0]
 [0 0 0 0 0]]


# 5. Create a numpy array that has the shape 3x5 and all the elements are 5.


In [28]:
# np.full is used to create array of any shape but all the elements as same

x= np.full( (3,5) , 5)    #(  (shape), element that you want)
print(x)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


# 7. Create a numpy array with a shape 3x3 that has all elements as 1.


In [ ]:
# 1st Method

# Homework try by using np.full

In [29]:
#2nd Methods
h=np.ones((3,3))
print(h)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# 6. Create a numpy array with random integers in the range 0-100, and the sample size should be 25

In [34]:
arr=np.random.randint( 0,100,25 )    # (start , end , how many numbers you want )
print(arr)

# rehape it to 2d array from 1d array
newarr = arr.reshape(5,5)
print(newarr)

[94 48 72 14 35 29 83 11 23 63  8 36 59 42  5 58 66  2  5 51 14 76 48 50
 50]
[[94 48 72 14 35]
 [29 83 11 23 63]
 [ 8 36 59 42  5]
 [58 66  2  5 51]
 [14 76 48 50 50]]


In [38]:
# directly create numpy array of shape 5,5 with random numbers between 0-100
arr=np.random.randint(0,100 ,size=(5,5))
print(arr)

[[67 38  3 70 37]
 [32 73 98  1 24]
 [19 91 80 47 52]
 [87 90 12 48 10]
 [43 70 39 72 93]]


# 8. Create a numpy array in the shape 2x3 with random integers in the range 0-100. Reshape the array in the shape 3x2 and print the updated shape of the resultant array.


In [ ]:
# Homework

# 9.
# step 1.Create a random array, with the range 0-1000, with a size 50
# step 2. Perform the following operations on the same.
#a. Print the first ten elements of the array.
#b. Print the last ten elements of the array
#c. Print the elements from the indexes 10-25
#d. Print the element at the index 22
#e. Print the array using negative indexing.
#f. Print the last ten elements of the array, using negative indexing.

In [42]:
arr=np.random.randint(0,1000,50)
print(arr)

[697 916 923 444 382 170 664 984 778 901 813 747 986  45 349 499 416 678
 960 252 939 284 924 699 534 821  38 364  19 523 425 426 516 348  47 264
 474 711 464 611 886 768 714 718 692  10 598 475 658 258]


In [43]:
#a Print the first ten elements of the array.
# Slicing operaton

print(arr[0 : 10 ])    #[start: end]

[697 916 923 444 382 170 664 984 778 901]


In [48]:
#b Print the last ten elements of the array

print(arr[ 40: ])
print(arr[-10: ])

[886 768 714 718 692  10 598 475 658 258]
[886 768 714 718 692  10 598 475 658 258]


In [49]:
#c. Print the elements from the indexes 10 to 25

print(arr[10:26])   # (start index : end index +1 )

[813 747 986  45 349 499 416 678 960 252 939 284 924 699 534 821]


In [51]:
# code check
random1000=np.random.randint(0,1000,50)
print(random1000)
print(random1000[-10:])#[start:end]
print(random1000[40:])#[start:end]

[479 988 892 486 904 360 387 869 145 447 694 550 248 214 452 442 527 927
 756 367 813 155 202 100  41 722 786 723 393 188 979  68 853 341 247 963
 459 210 485 399 465  75 595 601 920 498  59 227 936 640]
[465  75 595 601 920 498  59 227 936 640]
[465  75 595 601 920 498  59 227 936 640]


In [52]:
# d Print the element at the index 22

print(arr[22])   # Indexing operation

924


In [53]:
# e. Print the array using negative indexing.

print(arr[-50 : ])   # start : end +1

[697 916 923 444 382 170 664 984 778 901 813 747 986  45 349 499 416 678
 960 252 939 284 924 699 534 821  38 364  19 523 425 426 516 348  47 264
 474 711 464 611 886 768 714 718 692  10 598 475 658 258]


In [54]:
#f Print the last ten elements of the array, using negative indexing.
print(arr[-10: ])

[886 768 714 718 692  10 598 475 658 258]


# 10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
#a. Insert the element 6 at the end of the array.
#b. Insert the element 10 at the beginning of the array.
#c. Insert the element 30, before 4.
#d. Update the element 5 as 50.
#e. Delete the element 50 in the updated array.
#f. Create a function to search for the element 30.
#g. Sort the array in ascending order.

In [69]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [70]:
# a. Insert the element 6 at the end of the array.

newarr=np.append(arr,6)    #( arr in which you want to insert , element you want to insert)

print(newarr)

[1 2 3 4 5 6]


In [71]:
#b Insert the element 10 at the beginning of the array.

arr2=np.insert(newarr , 0 , 10 )   # (arr name , position , element)
print(arr2)

[10  1  2  3  4  5  6]


In [74]:
#c Insert the element 30, before  the element 4

#new=np.insert(arr2 ,4 ,30 )

position=np.where(arr2==4)[0]
new=np.insert(arr2 ,position ,30 )
print(new)

[10  1  2  3 30  4  5  6]


In [75]:
# How to search for index of any element in array

arr=np.array([3,45,643,78,5,6,7,8,9,10,12,34,56,78,98])
# I want to search the index of 56
print(np.where(arr==643))


# If there are more than 1
arr=np.array([3,45,643,78,5,6,7,8,9,643,10,12,34,56,78,98,643])
print(np.where(arr==643))

(array([2]),)
(array([ 2,  9, 16]),)


In [76]:
#d Update the element at index 5 as 50.
print(new)

new[5]=50
print(new)

[10  1  2  3 30  4  5  6]
[10  1  2  3 30 50  5  6]


In [78]:
# e Delete the element 50 in the updated array.

newarr= np.delete(new,np.where(new==50)[0])   #( name of array from which you want to delete , position of element that you want to delete)
print(newarr)

[10  1  2  3 30  5  6]


In [81]:
# Create a function to search for the element 30.

def search(newarr):
  for i in newarr:
    if i==30:
      print("present")

search(newarr)

present


In [82]:
# g. Sort the array in ascending order.

newarr.sort()

print(newarr)

[ 1  2  3  5  6 10 30]


In [87]:
# sort in descending order

descending_array=np.sort(newarr)[::-1]

print(descending_array)

[30 10  6  5  3  2  1]
